import { ShieldCard, BoosterPack } from './types';

export const allShieldCards: ShieldCard[] = [
  // Card 1: Greece Wildfire
  {
    id: 'card-greece-wildfire',
    name: 'Greece Wildfire',
    category: 'natural_disaster',
    rarity: 'common',
    region: 'Greek Islands',
    triggerCondition: 'Wildfire >500 hectares in Greek islands, Jul-Sep 2026',
    oracleSource: 'EFFIS / Copernicus',
    payoutAmount: 50,
    activeWindow: 'Jul 1 - Sep 30, 2026',
    expiresAt: '2026-09-30',
    editionNumber: 312,
    totalEditions: 5000,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 2.1,
    artGradient: 'from-orange-600 via-red-700 to-yellow-500',
    resolution: {
      trigger: 'Wildfire exceeds 500 hectares on any Greek island',
      oracleSource: 'European Forest Fire Information System (EFFIS)',
      oracleUrl: 'https://effis.jrc.ec.europa.eu',
      verificationMethod: 'Satellite-confirmed burned area data, updated every 24h',
      resolutionWindow: 'Within 48h of trigger event, confirmed by 2+ data sources',
      binaryQuestion: 'Did wildfire exceed 500 hectares on a Greek island between Jul 1 - Sep 30, 2026?',
    },
    odds: {
      estimatedProbability: 0.67,
      methodology: 'Based on EFFIS 10-year average: Greek island wildfires >500ha occurred in 7 of last 10 years',
      historicalRate: '7/10 years (2016-2025)',
      trend: 'increasing',
      trendNote: 'Climate data shows Mediterranean wildfire season extending 3 weeks earlier per decade',
    },
    news: [
      {
        headline: 'Mediterranean heat dome forecast for July 2026',
        source: 'EU Copernicus',
        date: 'Jun 15, 2026',
        impact: 'bullish',
        snippet: 'Copernicus Climate Change Service projects sustained temperatures 4-6C above seasonal average across the eastern Mediterranean through July.',
      },
      {
        headline: 'Greece deploys record firefighting fleet for summer 2026',
        source: 'Reuters',
        date: 'Jun 10, 2026',
        impact: 'bearish',
        snippet: 'Greece has mobilized its largest-ever firefighting fleet including 7 new Canadair aircraft and 12,000 seasonal firefighters ahead of peak season.',
      },
      {
        headline: '2025 Greek fire season was worst in 5 years',
        source: 'BBC',
        date: 'Oct 2, 2025',
        impact: 'bullish',
        snippet: 'Over 150,000 hectares burned across Greece in 2025, with major fires on Rhodes and Corfu forcing mass tourist evacuations.',
      },
    ],
    backstory: {
      summary: 'Greece experiences devastating wildfires almost every summer. In 2023, the Alexandroupolis wildfire was the EU\'s largest ever recorded at 96,000 hectares. In 2024, fires near Athens forced evacuations of 10,000+ people.',
      whyItMatters: 'Wildfires destroy homes, kill people, devastate tourism economies, and displace communities. Greek islands depend on summer tourism, and fires during peak season cause cascading economic damage.',
      historicalContext: 'The 2018 Mati fire killed 104 people near Athens. The 2023 Alexandroupolis fire burned for weeks. Rhodes evacuations in 2023 displaced 20,000 tourists. Mediterranean fire seasons are extending earlier each decade due to climate change.',
      currentSituation: 'Drought conditions persist across the Aegean. Greek civil protection upgraded fire readiness to highest level for summer 2026. Tourist bookings remain at record highs, increasing human-caused ignition risk.',
    },
    riskFactors: [
      'Record heat forecasts for Mediterranean summer 2026',
      'Persistent drought conditions since spring 2026',
      'Meltemi wind patterns amplify fire spread on islands',
      'Tourist season campfire and cigarette ignition risk',
      'Historical pattern: 7 of 10 years had qualifying fires',
      'Vegetation regrowth from 2023-2024 fires creates new fuel load',
    ],
    benefitExplainer: 'Hold this card through summer. If Greek islands burn >500ha, you receive 50 USDC automatically via oracle confirmation. No claim forms, no waiting.',
  },

  // Card 2: California Earthquake
  {
    id: 'card-california-quake',
    name: 'California Quake',
    category: 'natural_disaster',
    rarity: 'rare',
    region: 'California, USA',
    triggerCondition: 'Earthquake >5.0 magnitude in California, 2026',
    oracleSource: 'USGS',
    payoutAmount: 300,
    activeWindow: 'Jan 1 - Dec 31, 2026',
    expiresAt: '2026-12-31',
    editionNumber: 88,
    totalEditions: 1000,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 18.5,
    artGradient: 'from-amber-700 via-orange-800 to-red-900',
    resolution: {
      trigger: 'Earthquake >5.0 magnitude anywhere in California',
      oracleSource: 'United States Geological Survey (USGS)',
      oracleUrl: 'https://earthquake.usgs.gov',
      verificationMethod: 'USGS ShakeMap automated detection, confirmed by seismograph network',
      resolutionWindow: 'Within 24h of seismic event, USGS confirmation typically within minutes',
      binaryQuestion: 'Did a USGS-confirmed M5.0+ earthquake occur within California state boundaries in 2026?',
    },
    odds: {
      estimatedProbability: 0.45,
      methodology: 'USGS data shows California averages 4-5 M5.0+ events per year, but distribution is clustered. Some years have none.',
      historicalRate: '~4-5 events/year average (2010-2025)',
      trend: 'stable',
      trendNote: 'Seismic activity follows geological timescales. The Hayward Fault accumulates ~5mm/year of strain, considered overdue for rupture.',
    },
    news: [
      {
        headline: 'USGS: Hayward Fault overdue for major rupture',
        source: 'USGS',
        date: 'Mar 2026',
        impact: 'neutral',
        snippet: 'The USGS continues to assess the Hayward Fault as the most dangerous fault in the US, with a 33% probability of M6.7+ within 30 years.',
      },
      {
        headline: 'Minor swarm of M2-3 quakes near Parkfield, CA',
        source: 'USGS',
        date: 'Feb 18, 2026',
        impact: 'bullish',
        snippet: 'A swarm of 12 small earthquakes recorded near Parkfield, a known seismically active segment of the San Andreas Fault.',
      },
      {
        headline: 'California building codes updated for 2026',
        source: 'LA Times',
        date: 'Jan 5, 2026',
        impact: 'neutral',
        snippet: 'New retrofit requirements for soft-story buildings take effect, but seismic risk fundamentally unchanged.',
      },
    ],
    backstory: {
      summary: 'California sits on the San Andreas Fault system. The USGS estimates a 60% probability of M6.7+ in the SF Bay Area within 30 years. The last major CA quake was Ridgecrest (2019, M7.1).',
      whyItMatters: '40 million people live in California. A major earthquake can collapse infrastructure, trigger fires, and cause billions in damage. The Northridge quake (1994) caused $20B in damage, killing 57.',
      historicalContext: 'The 1906 SF earthquake devastated the city. Northridge (1994, M6.7) was the costliest US earthquake. Ridgecrest (2019, M7.1) was the strongest in 20 years. The Hayward Fault is considered the most dangerous in the US.',
      currentSituation: 'Minor seismic swarms detected in early 2026. Strain continues accumulating on major fault systems. California Earthquake Early Warning system (ShakeAlert) now covers the full state.',
    },
    riskFactors: [
      'San Andreas Fault system under continuous tectonic stress',
      'Hayward Fault considered overdue for major rupture',
      'Historical seismic pattern: M5.0+ occurs most years',
      'Pacific-North American plate boundary motion: 46mm/year',
      'Cascadia subduction zone interaction effects',
    ],
    benefitExplainer: 'California averages several M5.0+ earthquakes yearly. If one hits in 2026, your 300 USDC payout lands instantly via USGS oracle confirmation.',
  },

  // Card 3: Hurricane Atlantic
  {
    id: 'card-hurricane-atlantic',
    name: 'Hurricane Atlantic',
    category: 'natural_disaster',
    rarity: 'epic',
    region: 'US East Coast',
    triggerCondition: 'Cat 3+ hurricane makes US East Coast landfall, Jun-Nov 2026',
    oracleSource: 'NOAA',
    payoutAmount: 500,
    activeWindow: 'Jun 1 - Nov 30, 2026',
    expiresAt: '2026-11-30',
    editionNumber: 22,
    totalEditions: 250,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 45.0,
    artGradient: 'from-slate-700 via-blue-900 to-cyan-800',
    resolution: {
      trigger: 'Category 3+ hurricane makes US East Coast landfall',
      oracleSource: 'NOAA National Hurricane Center',
      oracleUrl: 'https://www.nhc.noaa.gov',
      verificationMethod: 'NHC official advisory confirming landfall location and sustained wind speed at Cat 3+ (111+ mph)',
      resolutionWindow: 'Within 24h of landfall, NHC advisory confirmation',
      binaryQuestion: 'Did a NHC-confirmed Category 3+ hurricane make landfall on the US Atlantic coast between Jun 1 - Nov 30, 2026?',
    },
    odds: {
      estimatedProbability: 0.22,
      methodology: 'Historical NHC data: Cat 3+ East Coast landfalls occur roughly once every 4-5 years. Above-average season forecasts increase probability.',
      historicalRate: '~22% in any given year (based on 1900-2025 data)',
      trend: 'increasing',
      trendNote: 'Atlantic sea surface temperatures remain at record highs. Warm SSTs fuel rapid intensification, making Cat 3+ storms more likely.',
    },
    news: [
      {
        headline: 'NOAA 2026 hurricane season forecast: above average',
        source: 'NOAA',
        date: 'May 22, 2026',
        impact: 'bullish',
        snippet: 'NOAA predicts 17-21 named storms, 8-11 hurricanes, and 4-6 major hurricanes for the 2026 Atlantic season.',
      },
      {
        headline: 'Atlantic sea surface temperatures remain elevated',
        source: 'NOAA',
        date: 'May 15, 2026',
        impact: 'bullish',
        snippet: 'SSTs in the Main Development Region running 0.8-1.2C above the 1991-2020 average, fueling conditions for rapid intensification.',
      },
      {
        headline: 'US Army Corps fortifies Miami-Dade flood barriers',
        source: 'AP',
        date: 'Apr 20, 2026',
        impact: 'neutral',
        snippet: '$3.4B flood barrier project reaches 60% completion. Reduces damage potential but does not prevent hurricane landfall.',
      },
    ],
    backstory: {
      summary: 'The 2024 hurricane season featured Hurricane Milton (Cat 5), which devastated Florida in October 2024. NOAA has predicted active seasons through mid-2020s due to warm Atlantic SSTs.',
      whyItMatters: 'A Cat 3+ landfall causes catastrophic damage: storm surge flooding, structural destruction, power outages lasting weeks. Hurricane Katrina (2005) killed 1,392 people and caused $125B in damage.',
      historicalContext: 'Cat 3+ US East Coast landfalls: Michael (2018, FL), Ida (2021, LA/NE), Milton (2024, FL). The 2020s have been a hyperactive period. Hurricane Ian (2022) caused $110B in damage.',
      currentSituation: 'La Nina pattern developing, which historically correlates with more active Atlantic seasons. SSTs at record highs in the Main Development Region.',
    },
    riskFactors: [
      'Record Atlantic sea surface temperatures',
      'La Nina pattern developing (reduces wind shear, allows storms to strengthen)',
      'Historical 2020s hyperactivity continuing',
      'Gulf Stream temperature anomalies feeding coastal storms',
      'Increased rapid intensification events (Cat 1 to Cat 4 in 24h)',
    ],
    benefitExplainer: 'Epic payout for a major event. If a Cat 3+ hurricane hits the US East Coast this season, 500 USDC lands in your wallet automatically.',
  },

  // Card 4: EU Flight Chaos
  {
    id: 'card-eu-flight-chaos',
    name: 'EU Flight Chaos',
    category: 'travel',
    rarity: 'uncommon',
    region: 'European Union',
    triggerCondition: '>500 flights cancelled across EU airspace in 24h, Q3 2026',
    oracleSource: 'Eurocontrol',
    payoutAmount: 100,
    activeWindow: 'Jul 1 - Sep 30, 2026',
    expiresAt: '2026-09-30',
    editionNumber: 201,
    totalEditions: 3000,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 5.8,
    artGradient: 'from-blue-600 via-cyan-500 to-blue-800',
    resolution: {
      trigger: 'Any single day where >500 flights cancelled across EU airspace',
      oracleSource: 'Eurocontrol Network Manager',
      oracleUrl: 'https://www.eurocontrol.int',
      verificationMethod: 'Eurocontrol daily network operations report, cross-referenced with FlightRadar24 data',
      resolutionWindow: 'Within 48h of qualifying day, Eurocontrol daily report confirmation',
      binaryQuestion: 'Did any single day in Q3 2026 see >500 flight cancellations across EU airspace per Eurocontrol data?',
    },
    odds: {
      estimatedProbability: 0.55,
      methodology: 'ATC strikes, weather events, and IT outages caused 500+ cancellation days in 3 of last 4 summers (2022-2025)',
      historicalRate: '3/4 summers (2022-2025)',
      trend: 'increasing',
      trendNote: 'Record passenger volumes combined with aging ATC infrastructure and chronic staffing shortages in French and Italian control centers',
    },
    news: [
      {
        headline: 'French ATC union threatens summer 2026 strike action',
        source: 'Le Monde',
        date: 'May 28, 2026',
        impact: 'bullish',
        snippet: 'SNCTA union rejected latest salary offer, setting stage for potential walkouts during peak July travel period.',
      },
      {
        headline: 'Eurocontrol forecasts record 11M flights for summer 2026',
        source: 'Eurocontrol',
        date: 'Apr 15, 2026',
        impact: 'bullish',
        snippet: 'More flights equals more fragility. System operating near maximum capacity leaves zero margin for disruptions.',
      },
      {
        headline: 'EU single sky reform delayed again',
        source: 'Financial Times',
        date: 'Mar 10, 2026',
        impact: 'bullish',
        snippet: 'The long-promised Single European Sky reform, which would modernize fragmented ATC systems, pushed back to 2028.',
      },
    ],
    backstory: {
      summary: 'European air travel disruptions are chronic. In summer 2023, Eurocontrol reported record delays. ATC strikes in France alone disrupted 300,000 flights in 2023.',
      whyItMatters: 'Flight cancellations strand millions of travelers, costing billions in lost bookings, hotel rebookings, and missed connections. Compensation claims under EU261 regulation add insult to airline losses.',
      historicalContext: 'In 2024, Heathrow had 3 separate multi-hour closures. French ATC strikes are near-annual. The 2023 NATS outage grounded all UK flights for hours. IT failures at multiple airlines caused chaos in 2022-2024.',
      currentSituation: 'Summer 2026 expected to break passenger records. French ATC union in dispute. Italian ATC understaffed. Thunderstorm frequency increasing with climate change.',
    },
    riskFactors: [
      'ATC strikes (France has struck during summer in 3 of last 4 years)',
      'Italian ATC chronic understaffing',
      'Summer thunderstorm disruptions across Central Europe',
      'IT system failures (airline and ATC)',
      'Airport capacity limits at major hubs',
      'Record passenger volumes strain every link in the chain',
    ],
    benefitExplainer: 'EU flights get chaotic every summer. If 500+ flights cancel on any single day Q3 2026, you get 100 USDC. Simple as that.',
  },

  // Card 5: Heathrow Shutdown
  {
    id: 'card-heathrow-shutdown',
    name: 'Heathrow Shutdown',
    category: 'travel',
    rarity: 'epic',
    region: 'London, UK',
    triggerCondition: 'Heathrow airport closes >24h, 2026',
    oracleSource: 'NATS / Heathrow',
    payoutAmount: 400,
    activeWindow: 'Jan 1 - Dec 31, 2026',
    expiresAt: '2026-12-31',
    editionNumber: 15,
    totalEditions: 200,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 32.0,
    artGradient: 'from-sky-700 via-indigo-600 to-blue-900',
    resolution: {
      trigger: 'Heathrow airport all-runway closure >24 consecutive hours',
      oracleSource: 'NATS / Heathrow Airport Holdings',
      oracleUrl: 'https://www.heathrow.com',
      verificationMethod: 'Official Heathrow status page + NATS airspace restriction NOTAM, confirmed by 2+ sources',
      resolutionWindow: 'Within 48h of closure end, official confirmation',
      binaryQuestion: 'Did Heathrow Airport experience a full closure (all runways) exceeding 24 consecutive hours in 2026?',
    },
    odds: {
      estimatedProbability: 0.09,
      methodology: 'Rare but documented: full closures happened 3 times in 15 years (volcanic ash 2010, snow 2010, extended NATS failure)',
      historicalRate: '~3 events in 15 years (2010-2025)',
      trend: 'stable',
      trendNote: 'Improved de-icing and snow procedures, but new risks from drone incursions and Icelandic volcanic activity offset improvements',
    },
    news: [
      {
        headline: 'Heathrow third runway construction timeline unclear',
        source: 'The Guardian',
        date: 'Feb 2026',
        impact: 'neutral',
        snippet: 'Planning delays continue for the controversial third runway expansion, leaving Heathrow operating at 98% capacity on two runways.',
      },
      {
        headline: 'UK Met Office: 2026 winter forecast uncertain after polar vortex shift',
        source: 'Met Office',
        date: 'Nov 2025',
        impact: 'neutral',
        snippet: 'Weakened polar vortex could bring Beast from the East-style cold snaps to the UK, but timing remains uncertain.',
      },
      {
        headline: 'Heathrow handles record 82M passengers in 2025',
        source: 'Heathrow Airport',
        date: 'Jan 2026',
        impact: 'neutral',
        snippet: 'Record throughput means any closure has maximum economic impact. Over 1,300 flights per day now depend on Heathrow staying open.',
      },
    ],
    backstory: {
      summary: 'Heathrow handles 82M+ passengers annually, the busiest airport in Europe. A 24h closure affects ~1,300 flights and ~250,000 passengers, cascading into days of disruption.',
      whyItMatters: 'Heathrow connects to 214 destinations. A full closure disrupts global aviation networks, strands hundreds of thousands of passengers, and costs airlines tens of millions per day.',
      historicalContext: 'Closed for 6 days during the 2010 Eyjafjallajokull volcanic ash crisis. Heavy snow caused multi-day closures in Dec 2010 and 2017. The Gatwick drone incursion (2018) showed how small threats can shut major airports.',
      currentSituation: 'Operating at near-maximum capacity. Iceland\'s Reykjanes volcanic system remains active with potential for ash-producing eruptions. Drone detection systems installed but not fully tested at scale.',
    },
    riskFactors: [
      'Icelandic volcanic eruptions (Reykjanes system active since 2021)',
      'Extreme weather: snow, fog, wind storms',
      'Drone incursions (Gatwick precedent)',
      'NATS IT system failures',
      'Industrial action by ground handlers or ATC',
      'Security incidents',
    ],
    benefitExplainer: 'Rare trigger, big payout. If Heathrow fully closes for 24+ hours in 2026, this card pays 400 USDC. Low probability, high reward.',
  },

  // Card 6: Festival Cancelled EU
  {
    id: 'card-festival-cancelled-eu',
    name: 'Festival Cancelled EU',
    category: 'event',
    rarity: 'rare',
    region: 'European Union',
    triggerCondition: 'Major music festival (10k+ capacity) cancelled in EU, Q3 2026',
    oracleSource: 'News aggregator',
    payoutAmount: 300,
    activeWindow: 'Jul 1 - Sep 30, 2026',
    expiresAt: '2026-09-30',
    editionNumber: 67,
    totalEditions: 800,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 22.0,
    artGradient: 'from-purple-600 via-fuchsia-500 to-pink-600',
    resolution: {
      trigger: 'Any music festival with 10,000+ capacity cancelled in EU/UK',
      oracleSource: 'Verified news aggregation (Reuters, BBC, local press)',
      oracleUrl: 'https://www.reuters.com',
      verificationMethod: 'Official cancellation announcement from festival organizer, confirmed by 2+ independent news sources',
      resolutionWindow: 'Within 72h of official announcement',
      binaryQuestion: 'Was any music festival with 10,000+ capacity officially cancelled in the EU/UK during Q3 2026?',
    },
    odds: {
      estimatedProbability: 0.77,
      methodology: 'At least one major EU festival has cancelled each quarter for 2 years running (2024-2025). 40+ festivals cancelled in 2025 alone.',
      historicalRate: '~75-80% per quarter (2024-2025 trend)',
      trend: 'increasing',
      trendNote: 'Rising production costs, insurance premiums, and artist fee inflation making mid-tier festivals economically unviable',
    },
    news: [
      {
        headline: 'Wireless Festival cancelled after Ye banned from UK',
        source: 'BBC',
        date: 'Apr 7, 2026',
        impact: 'neutral',
        snippet: 'Wireless Q3 already counted as a different card. But the trend of cancellations accelerating signals structural fragility.',
      },
      {
        headline: 'Festival Republic warns of "unsustainable" cost increases',
        source: 'Music Week',
        date: 'Mar 2026',
        impact: 'bullish',
        snippet: 'Major festival promoter warns that production costs have risen 40% since 2019, with insurance premiums doubling for outdoor events.',
      },
      {
        headline: 'European festival attendance down 12% from 2019 peak',
        source: 'IQ Magazine',
        date: 'Feb 2026',
        impact: 'bullish',
        snippet: 'Cost-of-living crisis reducing discretionary spending on festivals, particularly in UK, Germany, and France markets.',
      },
    ],
    backstory: {
      summary: '40+ festivals cancelled in 2025 alone across Europe. Wireless 2026 cancelled April 7 after Ye was banned from the UK. The era of guaranteed festival seasons ended in 2023.',
      whyItMatters: 'Festival cancellations leave ticket holders stranded with non-refundable travel costs. Artists lose income. Local economies lose tourist spending. Vendors and crews lose seasonal income.',
      historicalContext: 'COVID killed many festivals permanently. Post-COVID, rising costs, artist controversies, and weather have made cancellations structural. Boardmasters, Y Not, Bluedot all cancelled in recent years.',
      currentSituation: 'Festival insurance premiums at all-time highs. Multiple mid-tier UK and EU festivals financially precarious heading into summer 2026.',
    },
    riskFactors: [
      'Artist availability crises and controversy withdrawals',
      'Sponsor withdrawal (brand safety concerns)',
      'Extreme weather events during outdoor season',
      'Rising production and insurance costs',
      'Declining ticket sales for mid-tier festivals',
      'Political and social pressure on controversial bookings',
    ],
    benefitExplainer: 'Festivals cancel at record rates now. If any 10k+ EU festival cancels Q3 2026, 300 USDC payout. High probability, decent reward.',
  },

  // Card 7: Champions League Postponed
  {
    id: 'card-cl-postponed',
    name: 'CL Match Postponed',
    category: 'event',
    rarity: 'uncommon',
    region: 'Europe',
    triggerCondition: 'Any CL match postponed >24h, 2026-27 season',
    oracleSource: 'UEFA',
    payoutAmount: 100,
    activeWindow: 'Sep 2026 - Jun 2027',
    expiresAt: '2027-06-30',
    editionNumber: 410,
    totalEditions: 4000,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 4.2,
    artGradient: 'from-violet-700 via-purple-600 to-indigo-800',
    resolution: {
      trigger: 'Any Champions League match postponed >24 hours',
      oracleSource: 'UEFA Official',
      oracleUrl: 'https://www.uefa.com',
      verificationMethod: 'UEFA official match schedule update confirming postponement >24h from original kickoff',
      resolutionWindow: 'Within 48h of UEFA announcement',
      binaryQuestion: 'Was any 2026-27 Champions League match postponed by more than 24 hours from its original scheduled kickoff?',
    },
    odds: {
      estimatedProbability: 0.32,
      methodology: 'At least one CL postponement >24h occurred in 3 of the last 5 seasons (2021-2026)',
      historicalRate: '3/5 seasons (2021-2026)',
      trend: 'stable',
      trendNote: 'Climate change makes extreme weather more common at European venues, but UEFA has improved contingency planning',
    },
    news: [
      {
        headline: '2026-27 CL group stage draw includes Istanbul, Moscow-area alternatives',
        source: 'UEFA',
        date: 'Aug 2026',
        impact: 'neutral',
        snippet: 'Expanded 36-team format increases the number of matches and venues, mathematically increasing postponement probability.',
      },
      {
        headline: 'Climate change making European weather more extreme',
        source: 'Copernicus',
        date: 'Jun 2026',
        impact: 'bullish',
        snippet: 'Copernicus data shows extreme precipitation events up 23% in frequency across Western Europe since 2000.',
      },
    ],
    backstory: {
      summary: 'CL matches get postponed more than fans realize. Lyon vs Barcelona postponed in 2024 due to heavy snow. Inter vs Genoa postponed for flooding. Istanbul 2023 final had significant weather delays.',
      whyItMatters: 'CL postponements affect millions of traveling fans with non-refundable flights and hotels. Broadcasters lose scheduled slots. Betting markets must unwind positions.',
      historicalContext: 'The expanded 36-team format (2024+) means more matches in more venues across wider geography, increasing weather and logistics risk. Winter matchdays in Northern/Eastern European cities carry highest postponement risk.',
      currentSituation: 'UEFA contingency protocols improved after 2022 Paris final crowd crush, but weather postponements remain outside organizational control.',
    },
    riskFactors: [
      'Heavy snowfall at northern European venues (Nov-Feb)',
      'Flooding events at pitch level',
      'Stadium infrastructure failures',
      'Political/security situations at host cities',
      'Expanded format means more matches, more venue diversity, more risk',
    ],
    benefitExplainer: 'If any CL match gets postponed 24+ hours this season, you collect 100 USDC. A solid uncommon with decent historical hit rate.',
  },

  // Card 8: WHO Pandemic Alert
  {
    id: 'card-pandemic-alert',
    name: 'Pandemic Alert',
    category: 'health',
    rarity: 'legendary',
    region: 'Global',
    triggerCondition: 'WHO declares new Public Health Emergency of International Concern, 2026',
    oracleSource: 'WHO',
    payoutAmount: 1000,
    activeWindow: 'Jan 1 - Dec 31, 2026',
    expiresAt: '2026-12-31',
    editionNumber: 3,
    totalEditions: 50,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 120.0,
    artGradient: 'from-red-700 via-rose-600 to-pink-800',
    resolution: {
      trigger: 'WHO declares a NEW Public Health Emergency of International Concern',
      oracleSource: 'World Health Organization',
      oracleUrl: 'https://www.who.int',
      verificationMethod: 'WHO Director-General official statement declaring new PHEIC, published on WHO.int',
      resolutionWindow: 'Within 24h of WHO declaration',
      binaryQuestion: 'Did the WHO declare a new PHEIC (not continuation of existing) in calendar year 2026?',
    },
    odds: {
      estimatedProbability: 0.17,
      methodology: 'Since the PHEIC mechanism was established in 2005, WHO has declared 8 PHEICs. Average frequency: roughly one every 2-3 years.',
      historicalRate: '8 PHEICs in 20 years (~1 per 2.5 years)',
      trend: 'increasing',
      trendNote: 'Post-COVID era has seen more frequent declarations. Monkeypox declared twice (2022, 2024). Zoonotic spillover risk increasing with habitat destruction.',
    },
    news: [
      {
        headline: 'H5N1 bird flu human cases rising in Southeast Asia',
        source: 'WHO',
        date: 'Mar 2026',
        impact: 'bullish',
        snippet: 'WHO monitoring cluster of H5N1 cases with possible human-to-human transmission in Cambodia. Case fatality rate remains high at ~50%.',
      },
      {
        headline: 'WHO monitoring novel respiratory pathogen cluster in Central Africa',
        source: 'WHO',
        date: 'Feb 2026',
        impact: 'bullish',
        snippet: 'Unidentified respiratory illness cluster in DRC under investigation. Early genomic sequencing underway.',
      },
      {
        headline: 'Global pandemic preparedness funding falls short of targets',
        source: 'The Lancet',
        date: 'Jan 2026',
        impact: 'neutral',
        snippet: 'Only 30% of promised pandemic preparedness funding has materialized since 2023, leaving surveillance gaps in Sub-Saharan Africa and Southeast Asia.',
      },
    ],
    backstory: {
      summary: 'WHO declared COVID-19 a PHEIC in January 2020 (lasted until May 2023). Monkeypox was declared a PHEIC in July 2022 and again in August 2024. The declaration rate has accelerated.',
      whyItMatters: 'A PHEIC triggers international coordination, travel advisories, and emergency funding. For individuals, PHEICs mean potential lockdowns, travel disruptions, and economic upheaval. COVID caused $12.5T in global economic damage.',
      historicalContext: '8 PHEICs declared since 2005: H1N1 (2009), Polio (2014), Ebola (2014, 2019), Zika (2016), COVID-19 (2020), Monkeypox (2022, 2024). Each caused significant disruption.',
      currentSituation: 'H5N1 bird flu adapting toward mammalian transmission. Novel pathogen surveillance has gaps in developing nations. Antimicrobial resistance growing as a potential PHEIC trigger.',
    },
    riskFactors: [
      'H5N1 avian influenza adapting toward human transmission',
      'Novel pathogen emergence from deforestation and wildlife trade',
      'Antimicrobial resistance reaching crisis levels in some regions',
      'Bioterrorism risk (state and non-state actors)',
      'Weakened global surveillance due to post-COVID budget cuts',
      'Zoonotic spillover probability increasing with habitat destruction',
    ],
    benefitExplainer: 'Legendary card. If WHO declares a new PHEIC in 2026, 1000 USDC. The rarest trigger, the biggest payout. Only 50 editions exist.',
  },

  // Card 9: New Sanctions Wave
  {
    id: 'card-sanctions-wave',
    name: 'New Sanctions Wave',
    category: 'geopolitical',
    rarity: 'rare',
    region: 'Global',
    triggerCondition: 'EU or US imposes new country-level sanctions, Q3-Q4 2026',
    oracleSource: 'OFAC / EU Council',
    payoutAmount: 200,
    activeWindow: 'Jul 1 - Dec 31, 2026',
    expiresAt: '2026-12-31',
    editionNumber: 55,
    totalEditions: 600,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 14.0,
    artGradient: 'from-slate-600 via-zinc-700 to-gray-800',
    resolution: {
      trigger: 'EU or US imposes new country-level sanctions package (new country added OR major expansion)',
      oracleSource: 'OFAC (US) / EU Official Journal',
      oracleUrl: 'https://ofac.treasury.gov',
      verificationMethod: 'Published in Federal Register (US) or EU Official Journal. Must be new country designation or major expansion (50+ new entities).',
      resolutionWindow: 'Within 72h of official publication',
      binaryQuestion: 'Did the EU or US officially publish a new major country-level sanctions package in Q3-Q4 2026?',
    },
    odds: {
      estimatedProbability: 0.52,
      methodology: 'New sanctions rounds have occurred at least twice yearly since 2022. Geopolitical tensions show no signs of easing.',
      historicalRate: '2+ rounds/year since 2022',
      trend: 'stable',
      trendNote: 'Sanctions have become the primary Western tool for geopolitical pressure. New targets emerge regularly: currently monitoring Iran, Myanmar, Sudan situations.',
    },
    news: [
      {
        headline: 'US-Iran tensions remain elevated after 2026 military exchanges',
        source: 'Reuters',
        date: 'May 2026',
        impact: 'bullish',
        snippet: 'Proxy conflicts and maritime incidents in the Red Sea corridor keep sanctions expansion on the table.',
      },
      {
        headline: 'EU considers new sanctions framework for AI-enabled surveillance exports',
        source: 'Financial Times',
        date: 'Apr 2026',
        impact: 'bullish',
        snippet: 'Proposed framework would sanction companies selling AI surveillance tools to authoritarian regimes. Could trigger new country designations.',
      },
      {
        headline: 'G7 commits to coordinated sanctions enforcement',
        source: 'US State Department',
        date: 'Mar 2026',
        impact: 'neutral',
        snippet: 'G7 enforcement coordination mechanism signals continued sanctions activity but does not indicate specific new targets.',
      },
    ],
    backstory: {
      summary: 'EU/US sanctions cycles have accelerated since 2022. Russia sanctions remain the largest package ever. Iran, Myanmar, and Sudan have all seen expanded designations in 2024-2025.',
      whyItMatters: 'Sanctions disrupt global trade flows, freeze assets, and create compliance burdens. For individuals, sanctions can affect banking access, travel, and business relationships overnight.',
      historicalContext: 'Russia sanctions (2022-ongoing) froze $300B+ in central bank reserves. Iran sanctions expanded after JCPOA collapse. New rounds hit Myanmar, Sudan, and Houthi-linked entities in 2024-2025.',
      currentSituation: 'US-China tensions (Taiwan Strait), Iran conflict spillover, Russia-Ukraine ongoing. Multiple pressure points could trigger new packages. EU developing novel AI surveillance sanctions framework.',
    },
    riskFactors: [
      'Iran conflict escalation (Red Sea, nuclear program)',
      'US-China tensions over Taiwan, tech exports',
      'Russia-Ukraine conflict creating new sanction triggers',
      'African political crises (Sudan, Sahel region)',
      'New conflict emergence (potential triggers in multiple regions)',
    ],
    benefitExplainer: 'Geopolitics drives sanctions cycles. If EU or US impose a new major sanctions package Q3-Q4 2026, 200 USDC. History says this happens more often than not.',
  },

  // Card 10: Solana Down
  {
    id: 'card-solana-down',
    name: 'Solana Down',
    category: 'crypto',
    rarity: 'common',
    region: 'Global',
    triggerCondition: 'Solana mainnet down >6 consecutive hours, 2026',
    oracleSource: 'Solana Status',
    payoutAmount: 50,
    activeWindow: 'Jan 1 - Dec 31, 2026',
    expiresAt: '2026-12-31',
    editionNumber: 1800,
    totalEditions: 5000,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 3.5,
    artGradient: 'from-emerald-600 via-green-700 to-teal-800',
    resolution: {
      trigger: 'Solana mainnet-beta TPS drops to 0 for >6 consecutive hours',
      oracleSource: 'Solana Status Page / Validator Consensus Data',
      oracleUrl: 'https://status.solana.com',
      verificationMethod: 'Solana Explorer confirmed 0 TPS for 6+ consecutive hours, corroborated by validator consensus metrics',
      resolutionWindow: 'Within 24h of network recovery',
      binaryQuestion: 'Did Solana mainnet-beta experience 0 TPS for >6 consecutive hours at any point in 2026?',
    },
    odds: {
      estimatedProbability: 0.11,
      methodology: 'Post-Firedancer upgrade stability dramatically improved. No outages >2h since 2023. But network upgrades and client rollouts remain risk windows.',
      historicalRate: '0 qualifying events in 2024-2025 (post-upgrade)',
      trend: 'decreasing',
      trendNote: 'Firedancer multi-client architecture and improved validator performance have significantly reduced outage risk compared to 2022-2023 era',
    },
    news: [
      {
        headline: 'Firedancer v1.0 deployed to 40% of validators',
        source: 'Solana Foundation',
        date: 'Mar 2026',
        impact: 'bearish',
        snippet: 'Multi-client diversity reduces single point of failure risk. Network resilience at all-time high.',
      },
      {
        headline: 'Solana processes record 65k TPS in stress test',
        source: 'Helius',
        date: 'Feb 2026',
        impact: 'bearish',
        snippet: 'Successful stress test demonstrates network can handle extreme load without degradation.',
      },
      {
        headline: 'Network congestion during memecoin surge causes elevated fees but no outage',
        source: 'CoinDesk',
        date: 'Jan 2026',
        impact: 'neutral',
        snippet: 'Heavy memecoin trading caused fee spikes but the network maintained block production throughout.',
      },
    ],
    backstory: {
      summary: 'Solana experienced several outages in 2022-2023, the longest being 17 hours in February 2023. Since the Firedancer client launch and network upgrades, stability has improved dramatically.',
      whyItMatters: 'A Solana outage freezes billions in DeFi TVL, halts NFT trading, and blocks payments. Validators, dApps, and users all lose money during downtime. CrowdShield itself runs on Solana.',
      historicalContext: '2022 was the worst year: 5 outages, including 2 lasting 14+ hours. The Feb 2023 outage was the last major one. Firedancer and QUIC protocol upgrades stabilized the network significantly.',
      currentSituation: 'Network operating at record reliability. Firedancer adoption growing. But new client rollouts and major protocol upgrades remain theoretical risk windows.',
    },
    riskFactors: [
      'Client software bugs during version upgrades',
      'Consensus failures during validator set changes',
      'DDoS-like spam attacks exploiting new features',
      'Validator coordination issues during emergency patches',
      'Firedancer-Agave client incompatibility edge cases',
    ],
    benefitExplainer: 'Bet against Solana stability. If mainnet goes down 6+ hours in 2026, this common card pays 50 USDC. Low probability post-Firedancer, but non-zero.',
  },

  // Card 11: CEX Freeze
  {
    id: 'card-cex-freeze',
    name: 'CEX Freeze',
    category: 'crypto',
    rarity: 'rare',
    region: 'Global',
    triggerCondition: 'Top-10 CEX halts withdrawals >48h, 2026',
    oracleSource: 'On-chain monitoring',
    payoutAmount: 300,
    activeWindow: 'Jan 1 - Dec 31, 2026',
    expiresAt: '2026-12-31',
    editionNumber: 120,
    totalEditions: 1000,
    isTriggered: false,
    isExpired: false,
    currentMarketValue: 19.0,
    artGradient: 'from-green-700 via-emerald-800 to-lime-900',
    resolution: {
      trigger: 'Any top-10 CEX (by volume, per CoinGecko) halts all withdrawals for >48 consecutive hours',
      oracleSource: 'On-chain monitoring + Official exchange communications',
      oracleUrl: 'https://www.coingecko.com',
      verificationMethod: 'On-chain flow analysis showing zero outflows + official exchange announcement or status page confirming halt',
      resolutionWindow: 'Within 72h of withdrawal resumption or ongoing halt confirmation',
      binaryQuestion: 'Did any CoinGecko top-10 exchange (by volume) halt all withdrawals for >48 consecutive hours in 2026?',
    },
    odds: {
      estimatedProbability: 0.13,
      methodology: 'Post-FTX regulation has reduced risk but not eliminated. Hack/exploit scenarios remain plausible. Bybit had a temporary pause in 2024.',
      historicalRate: '1 qualifying event in 2022 (FTX), near-miss in 2024 (Bybit)',
      trend: 'decreasing',
      trendNote: 'Proof-of-reserves, regulatory oversight, and institutional custody reducing systemic risk. But single-exchange exploits remain possible.',
    },
    news: [
      {
        headline: 'SEC approves spot Bitcoin ETFs; institutional custody grows',
        source: 'SEC',
        date: 'Jan 2024',
        impact: 'bearish',
        snippet: 'Less retail dependency on CEX custody as institutional-grade alternatives expand.',
      },
      {
        headline: 'Proof-of-reserves becomes industry standard for top exchanges',
        source: 'The Block',
        date: 'Mar 2026',
        impact: 'bearish',
        snippet: 'All top-10 exchanges now publish monthly proof-of-reserves attestations, increasing transparency.',
      },
      {
        headline: 'Bybit 2024 security incident resolved within 12h',
        source: 'Bybit',
        date: 'Sep 2024',
        impact: 'neutral',
        snippet: 'Bybit paused withdrawals for 12 hours during a security investigation. Resolved without loss of funds but demonstrated ongoing vulnerability.',
      },
    ],
    backstory: {
      summary: 'FTX collapsed in November 2022, freezing $8B in customer funds. Celsius, Voyager, and BlockFi all froze withdrawals in 2022. Even post-regulation, risks persist.',
      whyItMatters: 'A CEX freeze means your funds are trapped. During FTX, users lost everything. Even temporary freezes during security incidents can trigger panic selling across all markets.',
      historicalContext: 'The 2022 contagion killed 5 major platforms. Mt. Gox (2014) took a decade to partially reimburse users. QuadrigaCX founder "died" with the only keys. Trust in centralized custody remains fragile.',
      currentSituation: 'Top exchanges have improved security and reserves transparency. But smart contract exploits, insider threats, and regulatory enforcement actions could still trigger extended freezes.',
    },
    riskFactors: [
      'Hacking/exploitation of hot wallets',
      'Regulatory enforcement actions (surprise asset freezes)',
      'Bank run scenarios triggered by social media panic',
      'Smart contract bugs in exchange infrastructure',
      'Sanctions compliance failures leading to forced freezes',
    ],
    benefitExplainer: 'If a top-10 exchange freezes withdrawals for 48+ hours in 2026, this card pays 300 USDC. Post-FTX risk is lower but non-zero.',
  },

  // Card 12: Wireless Cancelled (TRIGGERED)
  {
    id: 'card-wireless-cancelled',
    name: 'Wireless Cancelled',
    category: 'event',
    rarity: 'rare',
    region: 'London, UK',
    triggerCondition: 'Major UK music festival cancelled due to artist ban',
    oracleSource: 'UK Home Office / News',
    payoutAmount: 300,
    activeWindow: 'Jan 1 - Jul 15, 2026',
    expiresAt: '2026-07-15',
    editionNumber: 42,
    totalEditions: 800,
    isTriggered: true,
    isExpired: false,
    currentMarketValue: 300.0,
    artGradient: 'from-amber-500 via-yellow-600 to-orange-700',
    resolution: {
      trigger: 'Wireless Festival 2026 officially cancelled',
      oracleSource: 'UK Home Office / Festival Republic official statement',
      oracleUrl: 'https://www.gov.uk/government/organisations/home-office',
      verificationMethod: 'Official cancellation announcement confirmed by 3+ major news sources (BBC, Reuters, Guardian)',
      resolutionWindow: 'RESOLVED: April 7, 2026',
      binaryQuestion: 'Was Wireless Festival 2026 officially cancelled? YES - CONFIRMED April 7, 2026.',
    },
    odds: {
      estimatedProbability: 0.92,
      methodology: 'At time of cancellation, controversy score was 92/100. Sponsor exodus + government intervention made cancellation near-certain.',
      historicalRate: 'N/A - unique event',
      trend: 'stable',
      trendNote: 'RESOLVED. Controversy escalated from 35 to 92 in 7 days as sponsors fled and government acted.',
    },
    news: [
      {
        headline: 'Wireless Festival 2026 cancelled after Kanye West blocked from UK',
        source: 'BBC',
        date: 'Apr 7, 2026',
        impact: 'bullish',
        snippet: 'UK Home Office banned Ye from entering the country citing concerns over antisemitic statements and Nazi glorification. Festival Republic confirmed immediate cancellation.',
      },
      {
        headline: 'Pepsi ends decade-long Wireless sponsorship',
        source: 'Variety',
        date: 'Apr 5, 2026',
        impact: 'bullish',
        snippet: 'Pepsi became the first major sponsor to withdraw, triggering a cascade. Diageo, Rockstar Energy, and PayPal followed within 24 hours.',
      },
      {
        headline: 'UK PM Starmer: "deeply concerning" booking',
        source: 'NPR',
        date: 'Apr 5, 2026',
        impact: 'bullish',
        snippet: 'Prime Minister Keir Starmer publicly condemned the booking, signaling government willingness to act.',
      },
      {
        headline: 'David Schwimmer thanks sponsors for pulling out',
        source: 'Variety',
        date: 'Apr 6, 2026',
        impact: 'bullish',
        snippet: 'Actor David Schwimmer publicly thanked departing sponsors, amplifying pressure on remaining partners.',
      },
    ],
    backstory: {
      summary: 'Ye (Kanye West) was booked as headliner for all 3 nights of Wireless Festival 2026 at Finsbury Park, London. His history of antisemitic remarks and Nazi glorification triggered a cascade of sponsor withdrawals, political condemnation, and a UK travel ban.',
      whyItMatters: '50,000 ticket holders left stranded. Non-refundable flights and hotels not covered by ticket refund. Demonstrated how a single booking decision can destroy a major event within a week.',
      historicalContext: 'Wireless has been one of the UK\'s largest urban music festivals since 2005. This was the first full cancellation in its history. The speed of the controversy escalation (35 to 92 controversy score in 7 days) was unprecedented.',
      currentSituation: 'TRIGGERED April 7, 2026. All card holders received 300 USDC payout. Refunds processing for ticket face value. Travel costs not covered. Card now a collectible.',
    },
    riskFactors: [
      'RESOLVED - All risk factors materialized:',
      'Artist controversy (antisemitism, Nazi glorification)',
      'Sponsor exodus (Pepsi, Diageo, Rockstar, PayPal)',
      'Political pressure (PM Starmer condemnation)',
      'Government action (UK Home Office travel ban)',
    ],
    benefitExplainer: 'TRIGGERED. All holders received 300 USDC payout on April 7, 2026. This card is now a collectible with gold border, proof you held the right shield at the right time.',
  },
];

export const boosterPacks: BoosterPack[] = [
  {
    id: 'pack-starter',
    name: 'Starter Shield',
    price: 5,
    cardCount: 3,
    guaranteedMinRarity: 'common',
    season: 'Season 1: Chaos Season',
    description: '3 random Shield Cards. A cheap way to start your collection.',
  },
  {
    id: 'pack-standard',
    name: 'Standard Shield',
    price: 15,
    cardCount: 5,
    guaranteedMinRarity: 'uncommon',
    season: 'Season 1: Chaos Season',
    description: '5 cards with at least 1 guaranteed Uncommon.',
  },
  {
    id: 'pack-premium',
    name: 'Premium Shield',
    price: 25,
    cardCount: 5,
    guaranteedMinRarity: 'rare',
    season: 'Season 1: Chaos Season',
    description: '5 cards with at least 1 guaranteed Rare. Better odds for Epics.',
  },
  {
    id: 'pack-legendary',
    name: 'Legendary Shield',
    price: 100,
    cardCount: 10,
    guaranteedMinRarity: 'epic',
    season: 'Season 1: Chaos Season',
    description: '10 cards with at least 1 guaranteed Epic. Legendary possible.',
  },
];

// User owns 8 cards
export const userCollection: ShieldCard[] = [
  allShieldCards.find((c) => c.id === 'card-wireless-cancelled')!,
  allShieldCards.find((c) => c.id === 'card-greece-wildfire')!,
  allShieldCards.find((c) => c.id === 'card-eu-flight-chaos')!,
  allShieldCards.find((c) => c.id === 'card-california-quake')!,
  allShieldCards.find((c) => c.id === 'card-pandemic-alert')!,
  allShieldCards.find((c) => c.id === 'card-solana-down')!,
  { ...allShieldCards.find((c) => c.id === 'card-cl-postponed')!, isExpired: true, expiresAt: '2026-03-01' },
  { ...allShieldCards.find((c) => c.id === 'card-sanctions-wave')!, isExpired: true, expiresAt: '2026-02-15' },
];

// Demo pack result: 5 cards including the triggered Wireless
export const demoPackResult: ShieldCard[] = [
  allShieldCards.find((c) => c.id === 'card-greece-wildfire')!,
  allShieldCards.find((c) => c.id === 'card-eu-flight-chaos')!,
  allShieldCards.find((c) => c.id === 'card-wireless-cancelled')!,
  allShieldCards.find((c) => c.id === 'card-hurricane-atlantic')!,
  allShieldCards.find((c) => c.id === 'card-solana-down')!,
];
