import { EventData, Cover, Poll, FeedItem } from './types';

export const defaultPayouts: Record<string, number> = {
  cancellation: 300,
  delay: 100,
  headliner_changed: 200,
  weather_rain: 75,
  venue_changed: 150,
};

export const events: EventData[] = [
  {
    id: 'wireless-2026',
    name: 'Wireless Festival 2026',
    venue: 'Finsbury Park',
    city: 'London',
    date: 'July 10-12, 2026',
    imageUrl: '',
    ticketPrice: 85,
    ticketsSold: 38500,
    maxTickets: 50000,
    controversyScore: 92,
    organizerBond: 120000,
    organizerTrustTier: 'standard',
    coverTypes: ['cancellation', 'delay', 'headliner_changed', 'weather_rain', 'venue_changed'],
    isResolved: true,
    tags: ['Music', 'Festival', 'Outdoor'],
    backstory: {
      summary: "UK's largest urban music festival. 3 nights at Finsbury Park, London. Headlined by Ye, who was subsequently banned from the UK.",
      whyControversial: "Ye's history of antisemitic remarks and Nazi glorification triggered mass sponsor withdrawal (Pepsi, Diageo, Rockstar, PayPal), political condemnation from UK PM, and ultimately a Home Office travel ban.",
      timeline: [
        { date: 'Mar 31, 2026', event: 'Ye announced as headliner for all 3 nights', impact: 'Controversy score: 35' },
        { date: 'Apr 2, 2026', event: 'Campaign Against Antisemitism calls for ban', impact: '+12 to controversy' },
        { date: 'Apr 4, 2026', event: 'Pepsi withdraws decade-long sponsorship', impact: '+15 to controversy' },
        { date: 'Apr 5, 2026', event: 'Diageo, Rockstar, PayPal pull out. PM Starmer condemns.', impact: '+18 to controversy' },
        { date: 'Apr 6, 2026', event: "UK Home Office reviews Ye's entry permission", impact: '+10 to controversy' },
        { date: 'Apr 7, 2026', event: 'Home Office bans Ye. Wireless cancelled.', impact: 'RESOLVED: Cancelled' },
      ],
      stakeholders: ['Festival Republic (organizer)', 'Live Nation (parent company)', 'Finsbury Park venue', '50,000 ticket holders', 'Pepsi, Diageo, Rockstar, PayPal (ex-sponsors)'],
      currentStatus: 'Cancelled. Refunds being processed for ticket face value. Travel costs not covered.',
    },
    methodology: {
      controversyScoreExplainer: 'Score 0-100 calculated from: 40% algorithmic (news sentiment via GDELT/NewsAPI, social media volume, corporate signals like sponsor withdrawals), 30% market signal (cover purchase rate, price trajectory), 30% participant signal (ticket-holder polls weighted by Bayesian Truth Serum methodology).',
      coverPricingExplainer: "Cover price follows a bonding curve: Premium = BaseRate x PayoutAmount x ControversyMultiplier x DemandCurve x TimeDecay. Based on Hanson (2007) LMSR principles and Cartea et al. (2024) strategic bonding curve research. Early buyers pay less; price rises with demand, controversy, and proximity to event.",
      resolutionExplainer: "Binary resolution only. 'Event Cancelled: YES or NO.' Oracle confirms via official announcement + 2 independent news sources. Payout triggers automatically within same Solana transaction. No claim forms, no waiting period.",
      whatYouCanDo: [
        'Buy cancellation cover to protect your travel investment (flights, hotels)',
        'Choose payout tier matching your actual costs (100-1000 USDC)',
        'Trade Cover NFTs on secondary if you want to lock in profit before resolution',
        'Vote in community polls to contribute to controversy score accuracy',
        'Monitor controversy score to time your cover purchase (lower score = cheaper premium)',
      ],
    },
  },
  {
    id: 'rock-the-country-2026',
    name: 'Rock the Country 2026',
    venue: 'Anderson County Fairgrounds',
    city: 'Anderson, SC',
    date: 'Feb 28, 2026',
    imageUrl: '',
    ticketPrice: 95,
    ticketsSold: 12000,
    maxTickets: 20000,
    controversyScore: 78,
    organizerBond: 60000,
    organizerTrustTier: 'standard',
    coverTypes: ['cancellation', 'headliner_changed'],
    isResolved: true,
    tags: ['Music', 'Country', 'Political'],
    backstory: {
      summary: 'Country music festival in Anderson, SC featuring politically aligned artists. Multiple headliners withdrew over political controversies and safety concerns.',
      whyControversial: 'Festival marketed as politically conservative event. Headliner withdrawals (Shinedown, others) over political associations and safety concerns at outdoor venues created cascade of cancellations.',
      timeline: [
        { date: 'Jan 15, 2026', event: 'Rock the Country 2026 lineup announced', impact: 'Controversy score: 25' },
        { date: 'Feb 1, 2026', event: 'Shinedown withdraws citing "scheduling conflict"', impact: '+15 to controversy' },
        { date: 'Feb 10, 2026', event: 'Two more artists withdraw over political concerns', impact: '+20 to controversy' },
        { date: 'Feb 20, 2026', event: 'Safety concerns raised after venue inspection', impact: '+10 to controversy' },
        { date: 'Feb 25, 2026', event: 'Festival organizers announce cancellation', impact: 'RESOLVED: Cancelled' },
      ],
      stakeholders: ['Festival organizers', 'Anderson County Fairgrounds', '12,000 ticket holders', 'Booked artists and crew', 'Local businesses and vendors'],
      currentStatus: 'Cancelled. Partial refunds issued. Organizers citing force majeure.',
    },
    methodology: {
      controversyScoreExplainer: 'Score 0-100 calculated from: 40% algorithmic (news sentiment via GDELT/NewsAPI, social media volume, artist withdrawal signals), 30% market signal (cover purchase rate, price trajectory), 30% participant signal (ticket-holder polls weighted by Bayesian Truth Serum methodology).',
      coverPricingExplainer: "Cover price follows a bonding curve: Premium = BaseRate x PayoutAmount x ControversyMultiplier x DemandCurve x TimeDecay. Based on Hanson (2007) LMSR principles. Early buyers pay less; price rises with demand and controversy.",
      resolutionExplainer: "Binary resolution only. 'Event Cancelled: YES or NO.' Oracle confirms via official announcement + 2 independent news sources. Payout triggers automatically within same Solana transaction.",
      whatYouCanDo: [
        'Buy cancellation cover to protect your travel investment',
        'Monitor artist withdrawal announcements for early signals',
        'Trade Cover NFTs on secondary market',
        'Vote in community polls to improve controversy score accuracy',
      ],
    },
  },
  {
    id: 'ucl-final-2026',
    name: 'Champions League Final 2026',
    venue: 'Allianz Arena',
    city: 'Munich',
    date: 'May 31, 2026',
    imageUrl: '',
    ticketPrice: 250,
    ticketsSold: 64200,
    maxTickets: 65000,
    controversyScore: 15,
    organizerBond: 500000,
    organizerTrustTier: 'guaranteed',
    coverTypes: ['cancellation', 'delay', 'weather_rain'],
    isResolved: false,
    tags: ['Sport', 'Football'],
  },
  {
    id: 'breakpoint-2026',
    name: 'Solana Breakpoint 2026',
    venue: 'Marina Bay Sands',
    city: 'Singapore',
    date: 'Nov 2-4, 2026',
    imageUrl: '',
    ticketPrice: 45,
    ticketsSold: 3200,
    maxTickets: 5000,
    controversyScore: 5,
    organizerBond: 15000,
    organizerTrustTier: 'trusted',
    coverTypes: ['cancellation', 'venue_changed'],
    isResolved: false,
    tags: ['Conference', 'Crypto', 'Tech'],
  },
  {
    id: 'jazz-night-warsaw',
    name: 'Local Jazz Night',
    venue: 'Palladium',
    city: 'Warsaw',
    date: 'Apr 25, 2026',
    imageUrl: '',
    ticketPrice: 15,
    ticketsSold: 145,
    maxTickets: 200,
    controversyScore: 0,
    organizerBond: 500,
    organizerTrustTier: 'standard',
    coverTypes: ['cancellation'],
    isResolved: false,
    tags: ['Music', 'Jazz', 'Local'],
  },
];

export const wirelessPolls: Poll[] = [
  {
    id: 'poll-1',
    question: 'Will Ye actually perform?',
    options: [
      { label: 'YES', votes: 4340, percentage: 35 },
      { label: 'NO', votes: 5952, percentage: 48 },
      { label: 'Replaced', votes: 2108, percentage: 17 },
    ],
    totalVotes: 12400,
    endsAt: '2026-07-09T23:59:00Z',
  },
  {
    id: 'poll-2',
    question: 'Will more sponsors pull out?',
    options: [
      { label: 'YES', votes: 6408, percentage: 72 },
      { label: 'NO', votes: 2492, percentage: 28 },
    ],
    totalVotes: 8900,
    endsAt: '2026-07-08T23:59:00Z',
  },
  {
    id: 'poll-3',
    question: 'Expected attendance?',
    options: [
      { label: 'Under 20k', votes: 1550, percentage: 25 },
      { label: '20-35k', votes: 2790, percentage: 45 },
      { label: '35k+', votes: 1860, percentage: 30 },
    ],
    totalVotes: 6200,
    endsAt: '2026-07-10T12:00:00Z',
  },
];

export const wirelessFeed: FeedItem[] = [
  {
    id: 'f1',
    user: 'NewsBot',
    avatar: 'NB',
    action: 'Wireless Festival officially cancelled',
    detail: 'UK Home Office banned Ye from entering the country',
    timestamp: '12 min ago',
  },
  {
    id: 'f2',
    user: 'CrowdShield Oracle',
    avatar: 'CS',
    action: 'resolution confirmed: CANCELLED',
    detail: 'Payouts processing to all covered fans',
    timestamp: '10 min ago',
  },
  {
    id: 'f3',
    user: 'Sarah M.',
    avatar: 'SM',
    action: 'received 300 USDC payout',
    detail: 'Cancellation cover resolved',
    timestamp: '8 min ago',
  },
  {
    id: 'f4',
    user: 'JakeTheMusic',
    avatar: 'JT',
    action: 'received 300 USDC payout',
    detail: 'Paid 10.86, got 300 back',
    timestamp: '8 min ago',
  },
  {
    id: 'f5',
    user: 'Emma L.',
    avatar: 'EL',
    action: 'received 300 USDC payout',
    detail: 'Covered her group of 3',
    timestamp: '7 min ago',
  },
  {
    id: 'f6',
    user: 'FestivalWatch',
    avatar: 'FW',
    action: 'posted analysis',
    detail: '"This is exactly what CrowdShield was built for"',
    timestamp: '5 min ago',
  },
  {
    id: 'f7',
    user: 'LondonFanClub',
    avatar: 'LF',
    action: 'confirmed: flights + hotels non-refundable',
    detail: 'Cover payouts helping offset losses',
    timestamp: '3 min ago',
  },
  {
    id: 'f8',
    user: 'DJ_Marcus',
    avatar: 'DM',
    action: 'received 100 USDC payout',
    detail: 'Delay cover also resolved',
    timestamp: '2 min ago',
  },
];

export const userCover: Cover = {
  id: 'cover-001',
  eventId: 'wireless-2026',
  coverType: 'cancellation',
  premiumPaid: 10.86,
  payoutAmount: 300,
  isResolved: true,
  outcome: true,
  isClaimed: true,
  purchasedAt: '2026-03-15T14:30:00Z',
  currentMarketValue: 21.20,
};

export const userState = {
  hasTicket: true,
  eventId: 'wireless-2026',
  votedPolls: ['poll-1'],
};

export const coverCounts: Record<string, number> = {
  cancellation: 820,
  delay: 210,
  headliner_changed: 440,
  weather_rain: 155,
  venue_changed: 90,
};

export const priceHistory = [
  { day: 90, price: 3.2 },
  { day: 80, price: 3.4 },
  { day: 70, price: 4.1 },
  { day: 60, price: 5.8 },
  { day: 50, price: 7.2 },
  { day: 40, price: 8.9 },
  { day: 30, price: 11.5 },
  { day: 20, price: 14.2 },
  { day: 14, price: 15.8 },
  { day: 7, price: 17.1 },
  { day: 3, price: 18.0 },
  { day: 0, price: 21.2 },
];
